#!/bin/bash

# this is a very crude script that gets the stats from an hg612
# by blindly logging in over telnet and issuing the required
# commands.
# simply copy to your machines /etc/munins/plugins directory,
# make it runnable with "chmod ugo+x /etc/munins/plugins/hg612"
# and check it runs with "sudo munin-run hg612"
#
# Bugs: it blindly trusts that telnet works
#

HOST=192.168.1.1
USER=admin
PASS=admin

HGFILE=/var/run/munin/hg612.out

if [ "$1" = "config" ]; then
	echo "graph_title HG612 Stats on $HOST"
	echo "graph_category network"
	echo "graph_info This graph shows stats from the HG612 xDSL modem"
	echo "sync_up.label Sync speed up Mb/s"
	echo "sync_down.label Sync speed down Mb/s"
	echo "speed_up.label Speed Up Mb/s"
	echo "speed_down.label Speed down Mb/s"
	echo "SNR_up.label SNR up"
	echo "SNR_down.label SNR down"
	echo "ATTN_up.label Attenuation up dB"
	echo "ATTN_down.label Attenuation down dB"
	echo "PWR_up.label Power up dBm"
	echo "PWR_down.label Power down dBm"
	exit 0
fi

export PATH=/sbin:/usr/sbin:/bin:/usr/bin


#if /bin/false ; then
if /bin/true ; then
(
sleep 2
echo "$USER"
sleep 1
echo "$PASS"
sleep 1
echo sh
sleep 1
echo "xdslcmd info --stats"
sleep 3
exit
sleep 1
exit
) | telnet "$HOST" > "$HGFILE" 2>&1
#) | telnet "$HOST" 2>&1 | tee "$HGFILE"

fi

if [ ! -f "$HGFILE" -o ! -s "$HGFILE" ] ; then
	echo "Error, $HGFILE is missing or empty"
	exit 1
fi

#set -x

#Max:    Upstream rate = 7650 Kbps, Downstream rate = 47588 Kbps
#Bearer: 0, Upstream rate = 7787 Kbps, Downstream rate = 40000 Kbps


SYNC_UP=`awk '/^Max:/{ print $5 }' < "$HGFILE"`
SYNC_DN=`awk '/^Max:/{ print $10 }' < "$HGFILE"`
CURR_UP=`awk '/^Bearer:	0/{ print $6 }' < "$HGFILE"`
CURR_DN=`awk '/^Bearer:	0/{ print $11 }' < "$HGFILE"`

# scale the speeds down to megabits, otherwise the SNR values don't show
echo -n "sync_up.value "
echo "scale = 2 ; ( $SYNC_UP + 9.9 ) / 1000.0" | bc

echo -n "sync_down.value "
echo "scale = 2 ; ( $SYNC_DN + 9.9 ) / 1000.0" | bc

echo -n "speed_up.value "
echo "scale = 2 ; ( $CURR_UP + 9.9 ) / 1000.0" | bc

echo -n "speed_down.value "
echo "scale = 2 ; ( $CURR_DN + 9.9 ) / 1000.0" | bc


#                Down            Up
#SNR (dB):        6.9             3.8
#Attn(dB):        24.0            0.0
#Pwr(dBm):        12.0           -0.5
SNR_UP=`awk '/^SNR \(dB\):/{ print $4 }' < "$HGFILE"`
SNR_DN=`awk '/^SNR \(dB\):/{ print $3 }' < "$HGFILE"`
echo "SNR_up.value $SNR_UP"
echo "SNR_down.value $SNR_DN"

ATTN_UP=`awk '/^Attn\(dB\):/{ print $3 }' < "$HGFILE"`
ATTN_DN=`awk '/^Attn\(dB\):/{ print $2 }' < "$HGFILE"`
echo "ATTN_up.value $ATTN_UP"
echo "ATTN_down.value $ATTN_DN"

PWR_UP=`awk '/^Pwr\(dBm\):/{ print $3 }' < "$HGFILE"`
PWR_DN=`awk '/^Pwr\(dBm\):/{ print $2 }' < "$HGFILE"`
echo "PWR_up.value $PWR_UP"
echo "PWR_down.value $PWR_DN"


