#!/bin/bash

# this is a very crude script that gets the stats from an hg612
# by blindly logging in over telnet and issuing the required
# commands.
# simply copy to your machines /etc/munins/plugins directory,
# make it runnable with "chmod ugo+x /etc/munins/plugins/hg612"
# and check it runs with "sudo munin-run hg612"
#
# Bugs: it blindly trusts that telnet works
#

HOST=192.168.1.1
USER=admin
PASS=admin

HGFILE=/var/run/munin/hg612.out

if [ "$1" = "config" ]; then
	echo "graph_title HG612 Stats on $HOST"
	echo "graph_category network"
	echo "graph_info This graph shows stats from the HG612 xDSL modem"
	echo "sync_up.label Sync speed up"
	echo "sync_down.label Sync speed down"
	echo "speed_up.label Speed Up"
	echo "speed_down.label Speed down"
	echo "SNR_up.label SNR up"
	echo "SNR_down.label SNR down"
	exit 0
fi

export PATH=/sbin:/usr/sbin:/bin:/usr/bin


#if /bin/false ; then
if /bin/true ; then
(
sleep 2
echo "$USER"
sleep 1
echo "$PASS"
sleep 1
echo sh
sleep 1
echo "xdslcmd info --stats"
sleep 3
exit
sleep 1
exit
) | telnet "$HOST" > "$HGFILE" 2>&1
#) | telnet "$HOST" 2>&1 | tee "$HGFILE"

fi

if [ ! -f "$HGFILE" -o ! -s "$HGFILE" ] ; then
	echo "Error, $HGFILE is missing or empty"
	exit 1
fi

#set -x

#Max:    Upstream rate = 7650 Kbps, Downstream rate = 47588 Kbps
#Bearer: 0, Upstream rate = 7787 Kbps, Downstream rate = 40000 Kbps


MAX_UP=`awk '/^Max:/{ print $5 }' < "$HGFILE"`
MAX_DN=`awk '/^Max:/{ print $10 }' < "$HGFILE"`
CURR_UP=`awk '/^Bearer:	0/{ print $6 }' < "$HGFILE"`
CURR_DN=`awk '/^Bearer:	0/{ print $11 }' < "$HGFILE"`

#SNR (dB):        6.9             3.9

SNR_UP=`awk '/^SNR \(dB\):/{ print $3 }' < "$HGFILE"`
SNR_DN=`awk '/^SNR \(dB\):/{ print $4 }' < "$HGFILE"`

echo sync_up.value "$MAX_UP"
echo sync_down.value "$MAX_DN"
echo speed_up.value "$CURR_UP"
echo speed_down.value "$CURR_DN"
#echo SNR_up.value "$SNR_UP"
#echo SNR_down.value "$SNR_DN"


